version: "3"

services: 
    poll:
        build: ./poll
        command: python app.py
        ports: 
            - 5000:80
        networks: 
            - poll-tier

    redis:
        image: redis:alpine
        container_name: redis
        ports: 
            - 6379
        networks: 
            - poll-tier
            - back-tier
    
    worker:
        build: 
            context: ./worker
        depends_on: 
            - "redis"
            - "db"
        networks: 
            - back-tier
    
    db:
        image: postgres
        container_name: db
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes: 
            - "db-data:/var/lib/postgresql/data"
        networks: 
            - result-tier
            - back-tier
    
    result:
        build: ./result
        command: node Node.js
        ports: 
            - 5001:80
        networks: 
            - result-tier

volumes: 
    db-data:

networks: 
    poll-tier:
    result-tier:
    back-tier:
            